// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4fsTIjjCtF38QAKs4yjtBHujnWhnQiA',
    appId: '1:692621757313:web:cacb7e2c27ffe8de0b7680',
    messagingSenderId: '692621757313',
    projectId: 'login-55fe8',
    authDomain: 'login-55fe8.firebaseapp.com',
    storageBucket: 'login-55fe8.firebasestorage.app',
    measurementId: 'G-QG6NTH7ZKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKbVSldyRmPucQZuFd_lWEk0SfN54qnM',
    appId: '1:692621757313:android:de697db76c5bb2d50b7680',
    messagingSenderId: '692621757313',
    projectId: 'login-55fe8',
    storageBucket: 'login-55fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMAhMUXcMlbk6xcZxbRoaEb43z2_RAKY',
    appId: '1:692621757313:ios:487ca91a7f80d37c0b7680',
    messagingSenderId: '692621757313',
    projectId: 'login-55fe8',
    storageBucket: 'login-55fe8.firebasestorage.app',
    iosBundleId: 'com.example.portfolioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUMAhMUXcMlbk6xcZxbRoaEb43z2_RAKY',
    appId: '1:692621757313:ios:487ca91a7f80d37c0b7680',
    messagingSenderId: '692621757313',
    projectId: 'login-55fe8',
    storageBucket: 'login-55fe8.firebasestorage.app',
    iosBundleId: 'com.example.portfolioFlutter',
  );
}
